name: OTC GUI Login Smoke Test

on:
  workflow_dispatch:

  schedule:
    - cron: '30 8 * * *'

jobs:
  smoke-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install firefox

      - name: Run Smoke Test
        run: |
         xvfb-run python test.py
         
      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
         name: SmokeTestReport
         path: report.txt
